"""Added liabilities models

Revision ID: 371fb042ebf9
Revises: 008
Create Date: 2026-04-16 14:24:56.309479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371fb042ebf9'
down_revision: Union[str, Sequence[str], None] = '008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_liabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monthly_record_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monthly_record_id'], ['monthly_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['liability_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_liabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_liabilities_monthly_record_id'), ['monthly_record_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_account_number_hash'))
        batch_op.create_index(batch_op.f('ix_accounts_account_number_hash'), ['account_number_hash'], unique=True)

    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index('idx_category_rule_merchant', ['normalized_merchant'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_category_rule_merchant')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_account_number_hash'))
        batch_op.create_index(batch_op.f('ix_accounts_account_number_hash'), ['account_number_hash'], unique=False)

    with op.batch_alter_table('monthly_liabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_liabilities_monthly_record_id'))

    op.drop_table('monthly_liabilities')
    op.drop_table('monthly_records')
    op.drop_table('liability_templates')
    # ### end Alembic commands ###
