"""Add sort_order to MonthlyLiability

Revision ID: 65b8323be5e5
Revises: 371fb042ebf9
Create Date: 2026-04-16 14:53:29.649629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b8323be5e5'
down_revision: Union[str, Sequence[str], None] = '371fb042ebf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_liabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_liabilities', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
