"""add_user_model_and_user_id_fks

Revision ID: b8ab82914014
Revises: 65b8323be5e5
Create Date: 2026-04-16 18:59:58.543433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ab82914014'
down_revision: Union[str, Sequence[str], None] = '65b8323be5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Create users table if it doesn't already exist
    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=150), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=True),
        sa.Column('google_id', sa.String(length=150), nullable=True),
        sa.Column('profile_picture', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('google_id')
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        if 'ix_users_email' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    def _cols(table):
        return {c['name'] for c in inspector.get_columns(table)}

    # accounts.user_id
    if 'user_id' not in _cols('accounts'):
        with op.batch_alter_table('accounts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_accounts_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # advisor_reports.user_id — already a VARCHAR(100), convert to Integer FK
    with op.batch_alter_table('advisor_reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_advisor_reports_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # budgets.user_id
    if 'user_id' not in _cols('budgets'):
        with op.batch_alter_table('budgets', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_budgets_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # category_rules.user_id
    if 'user_id' not in _cols('category_rules'):
        with op.batch_alter_table('category_rules', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_category_rules_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_category_rules_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # insights.user_id
    if 'user_id' not in _cols('insights'):
        with op.batch_alter_table('insights', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_insights_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_insights_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # statements.user_id
    if 'user_id' not in _cols('statements'):
        with op.batch_alter_table('statements', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_statements_user_id'), ['user_id'], unique=False)
            batch_op.create_foreign_key('fk_statements_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_statements_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_insights_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_category_rules_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('advisor_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
